cmake_minimum_required(VERSION 3.25)

function(link_opengl target)
    if (APPLE)
        find_package(OpenGL REQUIRED)
        target_link_libraries(${target} PRIVATE OpenGL::GL)
        target_compile_definitions(${target} PUBLIC OPENGL_SUPPORTED=1 OPENGL_USES_GLAD=0)
    elseif (LINUX OR WIN32 OR UNIX)
        add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/ext/glad)
        target_include_directories(${target} PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/ext/glad/include)
        target_link_libraries(${target} PRIVATE glad)
        target_compile_definitions(${target} PUBLIC OPENGL_SUPPORTED=1 OPENGL_USES_GLAD=1)
    else()
        target_compile_definitions(${target} PUBLIC OPENGL_SUPPORTED=0)
    endif ()
endfunction()
