cmake_minimum_required(VERSION 3.25)

function(link_opengl target)
    if (APPLE)
        find_package(OpenGL REQUIRED)
        target_link_libraries(${PROJECT_NAME} PRIVATE OpenGL::GL)
    elseif (LINUX OR WIN32)
        add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/ext/glad)
        target_include_directories(${PROJECT_NAME} PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/ext/glad/include)
        target_link_libraries(${PROJECT_NAME} PRIVATE glad)
    endif ()
endfunction()
